spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    generate-ddl: true
  config:
    import: "aws-parameterstore:/spring-app/"
    activate:
      on-profile: prod
  data:
    redis:
      host: ${SPRING_REDIS_HOST}
      port: ${SPRING_REDIS_PORT}
  encryption:
    key: ${AES_128_ENCRYPTION_KEY}
  cloud:
    aws:
      s3:
        bucket: ${S3_IMAGE_SERVER}
        region: ap-northeast-2
      credentials:
        accessKey: ${AWS_ACCESS_KEY}
        secretKey: ${AWS_SECRET_KEY}


client:
  url: ${CLIENT_URL}
  localUrl: ${LOCAL_CLIENT_URL}
shortenUrlService:
  url: ${SPRING_SERVER_URL}