spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/jgs?serverTimezone=UTC"
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  config:
    activate:
      on-profile: local
  data:
    redis:
      host: localhost
      port: 6379
