spring:
  config:
    import: "aws-parameterstore:/spring-app"

  datasource:
    url: jdbc:mysql://172.31.91.139:3306/jgs
    username: spring_user
    password: Jgs1111!
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
