spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  config:
    import: "aws-parameterstore:/spring-app/"
    activate:
      on-profile: prod
  data:
    redis:
      host: ${SPRING_REDIS_HOST}
      port: ${SPRING_REDIS_PORT}
server:
  ssl:
    key-store: ${KEY-STORE}
    key-store-password: ${KEY-STORE-PASSWORD}
    keyStoreType: ${KEY-STORE-TYPE}
    keyAlias: ${KEY-ALIAS}
