spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: ${DB_MAX_POOL_SIZE:10}  # 기본값 10, 환경변수 DB_MAX_POOL_SIZE로 대체 가능
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    generate-ddl: true
  config:
    import: "aws-parameterstore:/spring-app/"
    activate:
      on-profile: prod
  data:
    redis:
      host: ${SPRING_REDIS_HOST}
      port: ${SPRING_REDIS_PORT}
  encryption:
    key: ${AES_128_ENCRYPTION_KEY}
  cloud:
    aws:
      s3:
        bucket: ${S3_IMAGE_SERVER}
        region: ap-northeast-2
  servlet:
    multipart:
      max-file-size: 10MB
  jwt:
    secretKey:
      ${JWT_SECRET_KEY}


client:
  url: ${CLIENT_URL}
  localUrl: ${LOCAL_CLIENT_URL}
shortenUrlService:
  url: ${SPRING_SERVER_URL}

management:
  endpoints:
    web:
      exposure:
        include: prometheus, health, info
  metrics:
    tags:
      application: ${spring.application.name}
