#spring:
#  config:
#    import: "aws-parameterstore:/spring-app/"
#
#aws:
#  paramstore:
#    enabled: true
#    prefix: /spring-app
#
#  datasource:
#    url: ${SPRING_DATASOURCE_URL}
#    username: ${SPRING_DATASOURCE_USERNAME}
#    password: ${SPRING_DATASOURCE_PASSWORD}
#    driver-class-name: com.mysql.cj.jdbc.Driver

#spring:
#  config:
#    # aws ParameterStore??? ?? ??
#    import: 'aws-parameterstore:'
#  datasource:
#    # ParameterStore? ??? ??
#    url: ${SPRING_DATASOURCE_URL}
#    username: ${SPRING_DATASOURCE_USERNAME}
#    password: ${SPRING_DATASOURCE_PASSWORD}
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL5Dialect
#
#aws:
#  paramstore:
#    enabled: true
#    prefix: /spring-app
#    # ??? ??? ?? ???
#    profile-separator: _

spring:
  config:
    import: "aws-parameterstore:/spring-app"

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
